name: Label & comment issues

on:
  issues:
    types: [reopened, opened]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Attach labels to issues
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })
      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue! We'll take a look as soon as possible.
        if: github.event.action == 'opened'

  comment_on_close:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on issue close
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The issue has been fixed. Thanks for reporting it!
        if: github.event.action == 'closed' && contains(github.event.issue.labels.*.name, 'fix')

  comment_on_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on first pull request
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thanks for opening your first pull request! We appreciate your contribution.
        if: github.event.action == 'opened' && github.event.pull_request.commits == 1
