name: Add comment when issue closed

on:
  issues:
    types: [closed]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Add comment
        uses: peter-evans/create-issue-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Thanks for using our product! We have resolved your issue. If you have any other questions, feel free to ask.'
