name: Add and close issue comments

on:
  issues:
    types: [opened, closed]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        uses: peter-evans/create-issue-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Thanks for opening this issue! We will take a look soon.'
        if: github.event.action == 'opened'

  close_comment:
    needs: add_comment
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        uses: peter-evans/create-issue-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'The issue has been resolved. Thanks!'
        if: github.event.action == 'closed'
