name: Add comment when issue opened/closed

on:
  issues:
    types: [opened, closed]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Thanks for opening this issue! We will take a look soon.'
        if: github.event.action == 'opened'

  close_comment:
    runs-on: ubuntu-latest
    needs: add_comment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'The issue has been resolved. Thanks!'
        if: github.event.action == 'closed'
