name: Label & Comment Issues

on:
  issues:
    types: [reopened, opened, closed]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Attach labels to issue
        uses: actions/github-script@v6
        with:
          script: |
            const labelsToAdd = ['issue'];
            if (github.event.action === 'closed' && github.context.payload.issue.labels.some(label => label.name === 'fix')) {
              labelsToAdd.push('closed');
            } else if (github.event.action === 'opened' && github.context.payload.issue.pull_request === undefined) {
              labelsToAdd.push('triage');
            }
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labelsToAdd
            })
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{
              github.event.action === 'closed' && github.context.payload.issue.labels.some(label => label.name === 'fix')
                ? 'Thanks for using this application. The issue has been resolved!'
                : github.event.action === 'opened' && github.context.payload.issue.pull_request === undefined
                ? 'Thanks for opening this issue! We\'ll take a look as soon as possible.'
                : ''
            }}
