name: Add comment when issue opened/closed

on:
  issues:
    types: [opened, closed]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          git clone https://github.com/peter-evans/create-issue-comment.git
          cd create-issue-comment
          git checkout v1
      - name: Add comment
        uses: ./create-issue-comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Thanks for opening this issue! We will take a look soon.'
        if: github.event.action == 'opened'

  close_comment:
    runs-on: ubuntu-latest
    needs: add_comment
    steps:
      - name: Install dependencies
        run: |
          git clone https://github.com/peter-evans/create-issue-comment.git
          cd create-issue-comment
          git checkout v1
      - name: Add comment
        uses: ./create-issue-comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'The issue has been resolved. Thanks!'
        if: github.event.action == 'closed'
