name: Label & comment issues # The name of the workflow
on:
  issues:
    types: [reopened, opened, closed] # This workflow will run when an issue is reopened, opened or closed
  pull_request_target:
    types: [opened] # This workflow will run when a user opens their first pull request

jobs:
  label_issues: # The job to label and comment on issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Attach label to issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })
      - name: Comment on new issue
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue! We'll take a look as soon as possible.

      - name: Comment on closed issue
        if: github.event_name == 'issues' && github.event.action == 'closed'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue has been closed. IWA sir t9awd!

      - name: Comment on new PR
        if: github.event_name == 'pull_request_target'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Congratulations on opening your first pull request! We appreciate your contribution to our project.
