name: Label & comment issues
on:
  issues:
    types: [reopened, opened]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Attach labels to issues
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })
      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue! We'll take a look as soon as possible.
      - name: Add comment when issue is closed
        uses: peter-evans/create-issue-comment@v1
        if: github.event.issue.state == 'closed'
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'The issue is now resolved by using GitHub workflows.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
